version: 2

sources:
- name: HPO_V2
  description: "HPO V2 Project"
  database: HPOV2_DB
  schema: RAW
  tables:
  - name: DIM_HOTELS
    columns:
    - name: property_id
      description: "The primary key for this table"
      data_tests:
      - unique
      - not_null

  - name: DIM_ROOMS
    columns:
    - name: room_id
      description: "The primary key for this table"
      data_tests:
      - unique
      - not_null

  - name: DIM_DATE
    columns:
    - name: date
      description: "The primary key for this table"
      data_tests:
      - unique
      - not_null
  - name: DIM_CUSTOMERS
    columns:
    - name: customer_id
      description: "The primary key for this table"
      data_tests:
      - unique
      - not_null
  - name: FACT_ROOM_INVENTORY
    data_tests:
    - dbt_utils.unique_combination_of_columns:
        arguments:
          combination_of_columns:
          - property_id
          - date_key
  - name: FACT_RESERVATIONS
    columns:
    - name: booking_id
      description: "The primary key for this table"
      data_tests:
      - unique
      - not_null
